import sqlite3
conn = sqlite3.connect('qr_attendance.db')
cur = conn.cursor()
print("--- Branches ---")
cur.execute('SELECT DISTINCT branch FROM subjects')
print("Subjects:", cur.fetchall())
cur.execute('SELECT DISTINCT branch FROM users')
print("Users:", cur.fetchall())
cur.execute('SELECT DISTINCT branch FROM timetable')
print("Timetable:", cur.fetchall())
print("\n--- Semesters ---")
cur.execute('SELECT DISTINCT semester FROM subjects')
print("Subjects:", cur.fetchall())
cur.execute('SELECT DISTINCT semester FROM users')
print("Users:", cur.fetchall())
cur.execute('SELECT DISTINCT semester FROM timetable')
print("Timetable:", cur.fetchall())
conn.close()
